apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    os: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu
  template:
    metadata:
      labels:
        os: ubuntu
    spec:
      containers:
      - image: ubuntu:xenial
        ports:
          - name: test-ports
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        args:
          ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
          - -cpus
          - "2"
  selector: 
      os: ubuntu
kind: Service
spec:
  clusterIP: 10.43.222.100
  externalIPs: 10.43.222.100
  ports:
  - nodePort: 30216
    port: 80
    protocol: TCP
    targetPort: test-ports
  selector:
    os: ubuntu
  type: NodePort
