apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  lables:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp-container
        image: ubuntu:xenial
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
          - name: testapp-ports
            containerPort: 888
        resources:
          limits:
            memory: 10Mi
#        args:
#          ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
#          - -cpus
#          - "2"
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  clusterIP: 10.233.0.2
  externalIPs: [80.11.12.10]
  ports:
  - protocol: TCP
    port: 888
    targetPort: testapp-ports
  selector:
    app: testapp
