apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: testApp-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: testApp
    template:
      metadata:
        labels:
          app: testApp
      spec:
        containers:
        - name: testApp-container
          image: ubuntu:xenial
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - name: testApp-ports
              containerPort:
          resources:
            limits:
              cpu: 0.1
              memory: 100Mi
          args:
            ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
            - -cpus
            - "2"
- apiVersion: v1
  kind: Service
  spec:
    clusterIP: 10.0.171.239
    externalIPs: 80.11.12.10
    ports:
    - nodePort: 30216
      protocol: TCP
      targetPort: test-ports
    selector:
      matchLabels:
        app: testApp
    type: NodePort
