apiVersion: v1
kind: Deployment
spec:
  replicas: 3
kind: Pod
spec:
  containers:
    image: polinux/stress:vi
    resources:
      limits:
        cpu: "0.1 GHz"
        memory: "500 MB"
  args:
    ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    - -cpus
    - "2"
kind: Service
spec:
  clusterIP: 10.0.171.239
  externalIP: 80.11.12.10
  ports:
    - protocol: TCP
      targetPort: my-pods
