apiVersion: v1
kind: Deployment
spec:
  strategy:
    type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 1
kind: Pod
spec:
  containers:
    image: polinux/stress
    resources:
      limits:
        cpu: "0,2"
        memory: "1gb"
  args:
    ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    - -cpus
    - "2"
kind: Service
spec:
  clusterIP: 10.0.171.239
  externalIP:
    - 80.11.12.10
  ports:
    - name: http
      port: 80
      targetPort: 9376
